---
abstract: 'BeLike::RJBS when you build your dists'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-RJBS
requires:
  Dist::Zilla: 2.100922
  Dist::Zilla::Plugin::AutoPrereq: 1.100130
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0
  Dist::Zilla::Plugin::GithubMeta: 0.12
  Dist::Zilla::Plugin::PodWeaver: 3.092971
  Dist::Zilla::Plugin::TaskWeaver: 0.093330
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Elemental: 0.092970
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver: 3.100310
  Pod::Weaver::Config::Assembler: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/rjbs/dist-zilla-pluginbundle-rjbs
  repository: https://github.com/rjbs/dist-zilla-pluginbundle-rjbs.git
version: 1.010
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@RJBS/Git::GatherDir'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RJBS/CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@RJBS/CheckExtraTests'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Filter/PruneCruft'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Filter/ManifestSkip'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Filter/MetaYAML'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Filter/License'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Filter/Readme'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Filter/ExecDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Filter/ShareDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RJBS/@Filter/MakeMaker'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Filter/Manifest'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Filter/TestRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Filter/ConfirmRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Filter/UploadToCPAN'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RJBS/AutoPrereqs'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RJBS/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@RJBS/TestMoreWithSubtests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RJBS/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@RJBS/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RJBS/@Git/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RJBS/@Git/Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RJBS/@Git/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RJBS/@Git/Push'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300015
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300015
