---
abstract: 'BeLike::RJBS when you build your dists'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100650'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-RJBS
requires:
  DateTime: 0
  Dist::Zilla: 1.092990
  Dist::Zilla::App: 0
  Dist::Zilla::Plugin::AutoPrereq: 1.100130
  Dist::Zilla::Plugin::PodWeaver: 3.092971
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::TaskWeaver: 0.093330
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Elemental: 0.092970
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver: 3.100310
  Test::More: 0
resources:
  repository: git://git.codesimply.com/Dist-Zilla-PluginBundle-RJBS.git
version: 0.100650
