---
abstract: 'BeLike::RJBS when you build your dists'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101620, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-RJBS
requires:
  DateTime: 0
  Dist::Zilla: 2.100922
  Dist::Zilla::App: 0
  Dist::Zilla::Plugin::AutoPrereq: 1.100130
  Dist::Zilla::Plugin::PodWeaver: 3.092971
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::TaskWeaver: 0.093330
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Elemental: 0.092970
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver: 3.100310
  Pod::Weaver::Config::Assembler: 0
resources:
  repository: git://git.codesimply.com/Dist-Zilla-PluginBundle-RJBS.git
version: 0.101620
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RJBS/@Basic/GatherDir'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Basic/PruneCruft'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Basic/ManifestSkip'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Basic/MetaYAML'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Basic/License'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Basic/Readme'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@RJBS/@Basic/ExtraTests'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Basic/ExecDir'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Basic/ShareDir'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RJBS/@Basic/MakeMaker'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Basic/Manifest'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Basic/TestRelease'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Basic/ConfirmRelease'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Basic/UploadToCPAN'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@RJBS/AutoPrereq'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@RJBS/AutoVersion'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@RJBS/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RJBS/PodWeaver'
      version: 3.101530
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RJBS/@Git/Check'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RJBS/@Git/Commit'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RJBS/@Git/Tag'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RJBS/@Git/Push'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereq:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101620
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101620
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 4.101620
